Demo-ASP/Controllers/LogementController.cs
using Demo_ASP.Handlers;
using Demo_ASP.Models.ClientViewModels;
using Demo_ASP.Models.LogementViewModels;
using Demo_BLL.Entities;
using Demo_Common.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace Demo_ASP.Controllers
{
    public class LogementController : Controller
    {
        private readonly ILogementRepository<Logement, int> _service;
        private readonly IClientRepository<Client, int> _serviceClient;
        private readonly IReservationRepository<Reservation, int> _serviceReservation;

        private readonly SessionManager _sessionManager;


        public LogementController(IReservationRepository<Reservation, int> serviceReservation ,IClientRepository<Client, int> serviceClient, ILogementRepository<Logement, int> service, SessionManager sessionManager)
        {
            _service = service;
            _serviceClient = serviceClient;
            _serviceReservation = serviceReservation;
            _sessionManager = sessionManager;
        }

        // GET: LogementController
        public ActionResult Index()
        {
            IEnumerable<LogementListItem> model = _service.Get().Select(e => e.ToListItem());

            return View(model);
        }

        //GET: LogementController/Details/5
        public ActionResult Details(int id)
        {
            LogementDetails model = _service.Get(id).ToDetails();
            if (model is null)
            {
                TempData["Error"] = "Logement inexistant...";
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult MyLogement()
        {
            IEnumerable<LogementListItem> model = _service.GetMyLogement(_sessionManager.CurrentUser.IdUser).Select(e => e.ToListItem());
           
            return View(model);
        }

        // GET: LogementController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LogementController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LogementCreateForm form)
        {
            if (!ModelState.IsValid) return View(form);
            form.Client_id = _sessionManager.CurrentUser.IdUser;
            form.date_add = DateTime.Now;
            int id = _service.Insert(form.ToBLL());
            return RedirectToAction("Details", new { id = id });
        }

        // GET: LogementController/Create
        public ActionResult SearchMonth()
        {
            var search = new LogementSearch();
            search.date = DateTime.Now;
            search.logements = new List<LogementListItem>();
            return View(search);
        }
        // POST: LogementController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchMonth(LogementSearch form)
        {
            IEnumerable<LogementListItem> model = _service.GetLogementMonth(form.date).Select(e => e.ToListItem());

            var search = new LogementSearch();
            search.logements = model;

            return View(search);
        }

        // GET: LogementController/Create
        public ActionResult SearchTwoDate()
        {
            var search = new LogementSearch();
            search.date_deb = DateTime.Now;
            search.date_fin = DateTime.Now;

            search.logements = new List<LogementListItem>();
            return View(search);
        }
        // POST: LogementController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult  SearchTwoDate(LogementSearch form)
        {
            IEnumerable<LogementListItem> model = _service.GetLogementTwoDate(form.date_deb,form.date_fin).Select(e => e.ToListItem());

            var search = new LogementSearch();
            search.logements = model;

            return View(search);
        }

        // GET: LogementController/Edit/5
        public ActionResult Edit(int id)
        {
            var logement = _service.Get(id).ToEdit();
           
            return View(logement);

        }

        // POST: LogementController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, LogementEditForm form)
        {
            if (!ModelState.IsValid) return View(form);
            if (!_service.Update(id, form.ToBLL()))
            {
                ViewBag.Error = "Erreur lors de la mise à jour... Réessayez";
                return View(form);
            }
            return RedirectToAction("Details", new { id = id });
        }

        // GET: LogementController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    LogementDelete model = _service.Get(id).ToDelete();
        //    if (model is null)
        //    {
        //        TempData["Error"] = "Logement inexistant...";
        //        return RedirectToAction("Index");
        //    }
        //    return View(model);
        //}

        public ActionResult Delete(int id)
        {
            var logement = _serviceReservation.GetReservationLogement(id);
            if(logement.Count() != 0) return RedirectToAction("MyLogement");

            bool e = _service.Delete(id);
            return RedirectToAction("Index");
        }

        // POST: LogementController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, LogementDelete form)
        //{
        //    if (!_service.Delete(id))
        //    {
        //        TempData["Error"] = "Erreur de suppression...";
        //    }
        //    return RedirectToAction("Index");
        //}
    }
}

Demo-ASP/Controllers/ReservationController.cs
using Demo_ASP.Handlers;
using Demo_ASP.Models.ClientViewModels;
using Demo_ASP.Models.ReservationViewModels;
using Demo_ASP.Models.LogementViewModels;
using Demo_BLL.Entities;
using Demo_Common.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo_ASP.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationRepository<Reservation, int> _service;
        private readonly IClientRepository<Client, int> _serviceClient;
        private readonly ILogementRepository<Logement, int> _serviceLogement;
        private readonly SessionManager _sessionManager;


        public ReservationController(IReservationRepository<Reservation, int> service,IClientRepository<Client, int> serviceClient, ILogementRepository<Logement, int> serviceLogement, SessionManager sessionManager)
        {
            _service = service;
            _serviceClient = serviceClient;
            _serviceLogement = serviceLogement;
            _sessionManager = sessionManager;
        }

        // GET: ReservationController
        //public ActionResult Index()
        //{
        //    IEnumerable<ReservationListItem> model = _service.Get().Select(e => e.ToListItem());

        //    return View(model);
        //}

        //GET: ReservationController/Details/5
        public ActionResult Details(int id)
        {


            ReservationDetails model = _service.Get(id).ToDetails();
            if (model is null)
            {
                TempData["Error"] = "Reservation inexistant...";
                return RedirectToAction("Index");
            }
            LogementDetails logement = _serviceLogement.Get(model.Logement_id).ToDetails();
            model.Logement_id = id;
            model.logement = logement;
            return View(model);
        }

        //public ActionResult MyReservation()
        //{
        //    IEnumerable<ReservationListItem> model = _service.GetMyReservation(_sessionManager.CurrentUser.IdUser).Select(e => e.ToListItem());

        //    return View(model);
        //}

        // GET: ReservationController/Create
        public ActionResult Create(int id)
        {
            LogementDetails model = _serviceLogement.Get(id).ToDetails();
            var form = new ReservationCreateForm();
            form.Logement_id = id;
            form.logement = model;

            return View(form);
        }

        public ActionResult MyReservation()
        {
            IEnumerable<ReservationListItem> model = _service.GetMyReservation(_sessionManager.CurrentUser.IdUser).Select(e => e.ToListItem());

            return View(model);
        }

        // POST: ReservationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReservationCreateForm form)
        {
            if (!ModelState.IsValid) 
                return View(form);
            form.Client_id = _sessionManager.CurrentUser.IdUser;
            form.Logement_id = form.Logement_id;
            int id = _service.Insert(form.ToBLL());
            return RedirectToAction("Details", new { id = id });
        }

        //GET: ReservationController/Edit/5
        public ActionResult Edit(int id)
        {
            var Reservation = _service.Get(id).ToEdit();
            LogementDetails model = _serviceLogement.Get(Reservation.Logement_id).ToDetails();

            Reservation.logement = model;
            return View(Reservation);

        }

        //POST: ReservationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ReservationEditForm form)
        {
            if (!ModelState.IsValid) return View(form);
            if (!_service.Update(id, form.ToBLL()))
            {
                ViewBag.Error = "Erreur lors de la mise à jour... Réessayez";
                return View(form);
            }
            return RedirectToAction("Details", new { id = id });
        }

        // GET: ReservationController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    ReservationDelete model = _service.Get(id).ToDelete();
        //    if (model is null)
        //    {
        //        TempData["Error"] = "Reservation inexistant...";
        //        return RedirectToAction("Index");
        //    }
        //    return View(model);
        //}

        public ActionResult Delete(int id)
        {
            bool e = _service.Delete(id);
            return RedirectToAction("MyReservation");
        }

        // POST: ReservationController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, ReservationDelete form)
        //{
        //    if (!_service.Delete(id))
        //    {
        //        TempData["Error"] = "Erreur de suppression...";
        //    }
        //    return RedirectToAction("Index");
        //}
    }
}

Demo-ASP/Views/Shared/_Layout.cshtml
@inject SessionManager sessionManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (sessionManager.CurrentUser != null)
                        {
                            /*
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CLient" asp-action="Index">Clients</a>
                            </li>
                            */
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Logement" asp-action="Index">Logements</a>
                        </li>
                    @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                       @* @if (sessionManager.CurrentUser is null)
                        {
                        <li class="float-right">
                            <a class="nav-link text-dark" asp-controller="Client" asp-action="login">Se connecter</a>
                        </li>
                        }
                        else
                        {
                        <li class="float-right">
                                <a class="nav-link text-dark" asp-controller="Client" asp-action="logout">@sessionManager.CurrentUser.Email | Se déconnecter</a>
                        </li>
                        }*@
                    </ul>
                    <ul class="navbar-nav float-right">
                        
                        @if (sessionManager.CurrentUser is null)
                        {
                            <li class="nav-item">
                                 <a class="nav-link text-dark" asp-controller="Client" asp-action="login">Se connecter</a>
                            </li>

                            <li class="nav-item">
                                 <a class="nav-link text-dark" asp-controller="Client" asp-action="create">Sign Up</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Logement" asp-action="MyLogement">Mes Annonces</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="MyReservation">Mes Reservations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" >@sessionManager.CurrentUser.Email</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Client" asp-action="logout">| Se déconnecter</a>
                            </li>

                        }
                        
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        @*
            OU
            
            @Html.Partial("_CookieConsentPartial")
        *@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 -EcoTravel App- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo-ASP/Views/Shared/_RepresentationList.cshtml
@model IEnumerable<DateTime>

<ul>
@foreach (DateTime repr in Model)
{
    <li>
        <div>Date : 
        <span>@repr.Date </span>
        Heure : 
        <span>@repr.TimeOfDay</span>
        </div>
    </li>
}
</ul>